apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-fastapi
  template:
    metadata:
      labels:
        app: demo-fastapi
    spec:
      containers:
        - name: demo-fastapi
          image: vctrmn/sample-fastapi:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
